### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by mrocklin** [milesgranger/gilknocker#16]
When I create a Coiled cluster with arm machines it complains if I have gilknocker installed

```
pip install gilknocker

import coiled
cluster = coiled.Cluster(arm=True)
```

I would like to use this on ARM if possible.  cc @milesgranger @ntabris

**Comment by ntabris** [comment]
I think that just needs a manylinux arm64 build and it will work.

**Comment by mrocklin** [comment]
Confirmed resolved.  Thanks all!
