### ISSUE TITLE
Add sampling interval

### ISSUE THREAD

**Issue by milesgranger** [milesgranger/gilknocker#9]
I was thinking about this implementation.
As we have it now, it needs to continuously poll at a fairly high rate (1ms) to get a reliable feel for how busy the GIL is when compared with `py-spy`.

Now I think if we have two intervals, a `sampling interval` and a `polling interval`. It won't need to poll continuously for the life of the monitoring but rather poll at the (potentially) high interval only for `sampling interval` example: it polls at 1ms intervals for 10ms sampling intervals.

I'd assume the same numerator used (time taken to get the GIL after requested) over instead of global time, but sum of polling intervals ought to give a pretty similar result but shouldn't be as taxing on programs. 

cc @fjetter

**Comment by fjetter** [comment]
So, just to wrap my head around this. we'd have a "Probe" running every `sampling interval` and this probe is running for `?` time every `polling interval` seconds trying to acquire the GIL? Something like


| --- Nothing for `sampling` ms --- | -<>-<>-poll every `polling`ms <>-<> -| -----Nothing -----|

**Comment by milesgranger** [comment]
That's exactly right.

**Comment by fjetter** [comment]
from a concept POV I think this is fine. It sounds easy enough to implement and I'd be curious to see if we can produce reasonably similar results.
The concern I have is that the benchmarks you are using are rather uniform in the way they are stressing a thread (specifically the `a_lotta_gil` function is very uniform. we may want to use something else for this. For example

```python
import random

def some_gil():    
    for i in range(10000):
        # On my machine the allocation of that KiB takes about 10-20us so
        # this sleep is about the same order of magnitude
        # Sleeping a bit more or allocating a bit more data will shift the GIL-measure in either
        # direction but the random sleep will make the measurement a bit harder
        time.sleep(random.random() / 100_000)
        b"1" * 1024**2
```
